version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    versions:
      applies-to: version-updates
    security:
      applies-to: security-updates
